/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package report.tool.gui;

import javax.swing.JOptionPane;
import report.tool.gui.database.DeliveryReportDao;
import report.tool.gui.database.ent.AddressConversionLog;
import report.tool.gui.database.ent.DeliveryReport;
import report.tool.gui.database.ent.MessageConversionLog;

/**
 *
 * @author andh
 */
public class CreateReportDialog extends javax.swing.JDialog {

    private final MessageConversionLog messageConversionLog;
    private final DeliveryReportDao deliveryReportDao = new DeliveryReportDao();

    /**
     * Creates new form CreateReportDialog
     */
    public CreateReportDialog(java.awt.Frame parent, MessageConversionLog messageConversionLog) {
        super(parent, true);
        initComponents();
        this.messageConversionLog = messageConversionLog;

        for (AddressConversionLog addressConversionLog : this.messageConversionLog.getAddressLogs()) {
            this.cboRecipient.addItem(addressConversionLog.getAddress());
        }
        
        this.txtSubjectID.setText(this.messageConversionLog.getMessageId());
    }

    private boolean validateForm() {
        if (txtNonDeliveryCode.getText() == null || txtNonDeliveryCode.getText().isEmpty()
                || txtNonDeliveryDiagnosticCode.getText() == null || txtNonDeliveryDiagnosticCode.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(this, "Chưa nhập dữ liệu !");
            return false;
        }

        try {
            Integer.parseInt(txtNonDeliveryCode.getText());
            Integer.parseInt(txtNonDeliveryDiagnosticCode.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showConfirmDialog(this, "Nhập dữ liệu sai !");
            return false;
        }

        return true;
    }
    
    private DeliveryReport parse() {
        DeliveryReport report = new DeliveryReport();
        report.setOriginator(this.messageConversionLog.getOrigin());
        report.setRecipient(this.cboRecipient.getSelectedItem().toString());
        // report.setSubjectId(this.messageConversionLog.getMessageId());
        report.setSubjectId(txtSubjectID.getText());
        report.setNonDeliveryReasonCode(Integer.parseInt(txtNonDeliveryCode.getText()));
        report.setNonDeliveryDiagnosticCode(Integer.parseInt(txtNonDeliveryDiagnosticCode.getText()));
        report.setSuplementInfo(txtSuplementInfo.getText());
        report.setEncodeInfomationType("ia5-text");
//        report.setPriority(1);
        return report;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboRecipient = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNonDeliveryCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNonDeliveryDiagnosticCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSuplementInfo = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSubjectID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Address");

        cboRecipient.setEditable(true);

        jLabel2.setText("Non Delivery Reason");

        txtNonDeliveryCode.setText("1");

        jLabel3.setText("Non Delivery Diagnostic Code");

        txtNonDeliveryDiagnosticCode.setText("1");

        jLabel4.setText("Suplement Info");

        btnCancel.setText("Cancel");

        btnSave.setText("OK");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel5.setText("Subject ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboRecipient, 0, 562, Short.MAX_VALUE)
                    .addComponent(txtSuplementInfo)
                    .addComponent(txtSubjectID)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNonDeliveryDiagnosticCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtNonDeliveryCode, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboRecipient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNonDeliveryCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNonDeliveryDiagnosticCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtSuplementInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {

                if (!validateForm()) {
                    return ;
                }
                
                DeliveryReport report = parse();
                deliveryReportDao.save(report);
                
                this.dispose();
                
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, "Lỗi ghi dữ liệu. " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboRecipient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtNonDeliveryCode;
    private javax.swing.JTextField txtNonDeliveryDiagnosticCode;
    private javax.swing.JTextField txtSubjectID;
    private javax.swing.JTextField txtSuplementInfo;
    // End of variables declaration//GEN-END:variables
}
